// <auto-generated />
using System;
using KinemaTrack.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace KinemaTrack.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250726204731_AddJointEntity")]
    partial class AddJointEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KinemaTrack.Domain.Entities.Joint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<double>("Angle")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("JointNumber")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("LinkLength")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<Guid>("RobotArmId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("RobotArmId");

                    b.ToTable("Joints");
                });

            modelBuilder.Entity("KinemaTrack.Domain.Entities.RobotArm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("RobotArms");
                });

            modelBuilder.Entity("KinemaTrack.Domain.Entities.Joint", b =>
                {
                    b.HasOne("KinemaTrack.Domain.Entities.RobotArm", "RobotArm")
                        .WithMany("Joints")
                        .HasForeignKey("RobotArmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RobotArm");
                });

            modelBuilder.Entity("KinemaTrack.Domain.Entities.RobotArm", b =>
                {
                    b.Navigation("Joints");
                });
#pragma warning restore 612, 618
        }
    }
}
